/*
DEFINE_MESSAGE(0x0000, TEXTBOX_TYPE_BLUE, TEXTBOX_POS_BOTTOM,
MSG("japanese")
,
MSG("english")
,
MSG("german")
,
MSG("french")
)
*/

DEFINE_MESSAGE(0x0301, TEXTBOX_TYPE_WOODEN, TEXTBOX_POS_BOTTOM,
MSG("japanese")
,
MSG(
	COLOR(YELLOW)
	"Hey! It's the dev, " COLOR(DEFAULT) "AbdooOwd" COLOR(YELLOW) "."
	BOX_BREAK
	COLOR(YELLOW)
	"Thanks for playing the mod!\n"
	"I had this idea for some time.\n"
	BOX_BREAK
	COLOR(YELLOW)
	"Enjoy!"
)
,
MSG("german")
,
MSG("french")
)

DEFINE_MESSAGE(0x302, TEXTBOX_TYPE_BLUE, TEXTBOX_POS_BOTTOM,
MSG("japanese")
,
MSG(
	"Welcome, bud!"
	BOX_BREAK
	"You know what's my favorite music?"
	BOX_BREAK
	"\"North Great Plains\" from\n"
	"the Indigo OST"
	BOX_BREAK
	"It's nice, no?"
	SWITCH_SPEAKER
	BOX_BREAK
	"Nuh uh"
	SWITCH_SPEAKER
	BOX_BREAK
	"Bruh"
)
,
MSG("german")
,
MSG("french")
)


// Ocarina stuff

DEFINE_MESSAGE(0x086D, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(60) "Play using " COLOR(BLUE) "[A]" COLOR(DEFAULT) " and " COLOR(YELLOW) "[C]" COLOR(DEFAULT) "." COLOR(YELLOW) "\n"
COLOR(DEFAULT) "\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(56) "Spiele die Melodien\n"
SHIFT(59) "mit " COLOR(ADJUSTABLE) "[A]" COLOR(DEFAULT) " und " COLOR(YELLOW) "[C]" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(45) "Jouez avec " COLOR(ADJUSTABLE) "[A]" COLOR(DEFAULT) " et " COLOR(YELLOW) "[C]" COLOR(DEFAULT) "." COLOR(YELLOW) "\n"
COLOR(DEFAULT) "\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x086E, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE "Play using " COLOR(BLUE) "[A]" COLOR(DEFAULT) " and " COLOR(YELLOW) "[C]" COLOR(DEFAULT) "; " COLOR(ADJUSTABLE) "[B]" COLOR(DEFAULT) " to Stop.\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(41) "Spiele mit " COLOR(ADJUSTABLE) "[A]" COLOR(DEFAULT) " und " COLOR(YELLOW) "[C]" COLOR(DEFAULT) ".\n"
SHIFT(27) "Drücke" COLOR(ADJUSTABLE) " " COLOR(RED) "[B]" COLOR(DEFAULT) ", um zu beenden.\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE COLOR(ADJUSTABLE) "[A]" COLOR(DEFAULT) " et " COLOR(YELLOW) "[C] " COLOR(DEFAULT) "- Jouer " COLOR(ADJUSTABLE) "   " COLOR(RED) "[B]" COLOR(ADJUSTABLE) " " COLOR(DEFAULT) "- Annuler\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x086F, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
"\n"
"\n"
OCARINA
)
,
MSG(
"\n"
"\n"
OCARINA
)
,
MSG(
"\n"
"\n"
OCARINA
)
)

DEFINE_MESSAGE(0x0870, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(22) "Play the " COLOR(ADJUSTABLE) "Minuet of Forest" COLOR(DEFAULT) "!" COLOR(ADJUSTABLE) "\n"
"\n"
"\n"
COLOR(DEFAULT) QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Spiele das " COLOR(ADJUSTABLE) "Menuett des Waldes" COLOR(DEFAULT) "." COLOR(ADJUSTABLE) "\n"
"\n"
"\n"
COLOR(DEFAULT) QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(25) "Jouez le " COLOR(ADJUSTABLE) "Menuet des bois" COLOR(DEFAULT) "." COLOR(ADJUSTABLE) "\n"
"\n"
"\n"
COLOR(DEFAULT) QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x0871, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(31) "Play the " COLOR(RED) "Bolero of Fire" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Spiele den " COLOR(RED) "Bolero des Feuers" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(32) "Jouez le " COLOR(RED) "Boléro du feu" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x0872, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(17) "Play the " COLOR(BLUE) "Serenade of Water" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Spiele die " COLOR(BLUE) "Serenade des Wassers" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(21) "Jouez la " COLOR(BLUE) "Sérénade de l'eau" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x0873, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(21) "Play the " COLOR(YELLOW) "Requiem of Spirit" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Spiele das " COLOR(YELLOW) "Requiem der Geister" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(15) "Jouez le " COLOR(YELLOW) "Requiem des esprits" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x0874, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(13) "Play the " COLOR(PURPLE) "Nocturne of Shadow" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Spiele die " COLOR(PURPLE) "Nocturne des Schattens" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(15) "Jouez le " COLOR(PURPLE) "Nocturne de l'ombre" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x0875, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(25) "Play the " COLOR(LIGHTBLUE) "Prelude of Light" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Spiele die " COLOR(LIGHTBLUE) "Kantate des Lichts" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(12) "Jouez le " COLOR(LIGHTBLUE) "Prélude de la lumière" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x0876, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(11) "Follow along with " COLOR(ADJUSTABLE) "Saria's Song" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Spiele geschwind " COLOR(ADJUSTABLE) "Salias Lied" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(26) "Jouez le " COLOR(ADJUSTABLE) "Chant de Saria" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x0877, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(32) "OK? This is " COLOR(RED) "the Song" COLOR(DEFAULT) "...\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Okay? Hier ist " COLOR(RED) "Eponas Lied" COLOR(DEFAULT) "...\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(33) "OK? Voici la" COLOR(RED) " mélodie" COLOR(DEFAULT) "...\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x0878, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(39) "Memorize " COLOR(BLUE) "this song" COLOR(DEFAULT) "...\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Präge Dir " COLOR(BLUE) "Zeldas Wiegenlied" COLOR(DEFAULT) " ein...\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(33) "Retiens cette " COLOR(BLUE) "mélodie" COLOR(DEFAULT) "...\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x0879, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE "Keep the " COLOR(YELLOW) "Sun's Song " COLOR(DEFAULT) "in your heart.\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Spiele die " COLOR(YELLOW) "Hymne der Sonne" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Retiens à jamais le " COLOR(YELLOW) "Chant du Soleil" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x087A, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE COLOR(LIGHTBLUE) "This song" COLOR(DEFAULT) " opens the Door of Time...\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE COLOR(LIGHTBLUE) "Dies Lied" COLOR(DEFAULT) " öffnet das Zeitportal...\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE COLOR(LIGHTBLUE) "Ce chant" COLOR(DEFAULT) " ouvre la Porte du Temps.\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x087B, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(23) "I'll never forget " COLOR(PURPLE) "this song" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Nie werde ich " COLOR(PURPLE) "dies Lied" COLOR(DEFAULT) " vergessen!\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Je n'oublierai jamais cette " COLOR(PURPLE) "mélodie" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x087C, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE "Play using " COLOR(BLUE) "[A]" COLOR(DEFAULT) " and " COLOR(YELLOW) "[C]" COLOR(DEFAULT) "; " COLOR(ADJUSTABLE) "[B]" COLOR(DEFAULT) " to Stop.\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE "Spiele mit " COLOR(ADJUSTABLE) "[A]" COLOR(DEFAULT) " und " COLOR(YELLOW) "[C]" COLOR(DEFAULT) ";\n"
COLOR(RED) "[B]" COLOR(DEFAULT) " zum Beenden.\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
,
MSG(
QUICKTEXT_ENABLE COLOR(ADJUSTABLE) "[A]" COLOR(DEFAULT) " et " COLOR(YELLOW) "[C] " COLOR(DEFAULT) "- Jouer " COLOR(ADJUSTABLE) "   " COLOR(RED) "[B]" COLOR(ADJUSTABLE) " " COLOR(DEFAULT) "- Annuler\n"
"\n"
"\n"
QUICKTEXT_DISABLE OCARINA
)
)

DEFINE_MESSAGE(0x088B, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
BACKGROUND(X_LEFT, ORANGE, BLACK, 1, 0) PERSISTENT
)
,
MSG(
BACKGROUND(X_LEFT, ORANGE, BLACK, 1, 0) PERSISTENT
)
,
MSG(
BACKGROUND(X_LEFT, ORANGE, BLACK, 1, 0) PERSISTENT
)
)

DEFINE_MESSAGE(0x0893, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(5) "You played the " COLOR(ADJUSTABLE) "Minuet of Forest" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE COLOR(ADJUSTABLE) "Menuett des Waldes " COLOR(DEFAULT) "gespielt!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(6) "Vous jouez le " COLOR(ADJUSTABLE) "Menuet des bois" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
)

DEFINE_MESSAGE(0x0894, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(14) "You played the " COLOR(RED) "Bolero of Fire" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE COLOR(RED) "Bolero des Feuers " COLOR(DEFAULT) "gespielt!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(16) "Vous jouez le " COLOR(RED) "Boléro du feu" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
)

DEFINE_MESSAGE(0x0895, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE "You played the " COLOR(BLUE) "Serenade of Water" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE COLOR(BLUE) "Serenade des Wassers " COLOR(DEFAULT) "gespielt!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(5) "Vous jouez la " COLOR(BLUE) "Sérénade de l'eau" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
)

DEFINE_MESSAGE(0x0896, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(4) "You played the " COLOR(YELLOW) "Requiem of Spirit" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE COLOR(YELLOW) "Requiem der Geister " COLOR(DEFAULT) "gespielt!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE "Vous jouez le " COLOR(YELLOW) "Requiem des esprits" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
)

DEFINE_MESSAGE(0x0897, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(9) "Played the " COLOR(PURPLE) "Nocturne of Shadow" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE COLOR(PURPLE) "Nocturne des Schattens " COLOR(DEFAULT) "gespielt!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE "Vous jouez le " COLOR(PURPLE) "Nocturne de l'ombre" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
)

DEFINE_MESSAGE(0x0898, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(8) "You played the " COLOR(LIGHTBLUE) "Prelude of Light" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE COLOR(LIGHTBLUE) "Kantate des Lichts " COLOR(DEFAULT) "gespielt!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE "Vous jouez le " COLOR(LIGHTBLUE) "Prélude de la lumière" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
)

DEFINE_MESSAGE(0x0899, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(30) "You played " COLOR(ADJUSTABLE) "Saria's Song" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE COLOR(ADJUSTABLE) "Salias Lied " COLOR(DEFAULT) "gespielt!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(12) "Vous jouez le " COLOR(ADJUSTABLE) "Chant de Saria" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
)

DEFINE_MESSAGE(0x089A, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(28) "You played " COLOR(RED) "Epona's Song" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE COLOR(RED) "Eponas Lied " COLOR(DEFAULT) "gespielt!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(15) "Vous jouez le " COLOR(RED) "Chant d'Epona" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
)

DEFINE_MESSAGE(0x089B, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(24) "You played " COLOR(BLUE) "Zelda's Lullaby" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE COLOR(BLUE) "Zeldas Wiegenlied" COLOR(DEFAULT) " gespielt!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(3) "Vous jouez la " COLOR(BLUE) "Berceuse de Zelda" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
)

DEFINE_MESSAGE(0x089C, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(22) "You played the " COLOR(YELLOW) "Sun's Song" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE COLOR(YELLOW) "Hymne der Sonne" COLOR(DEFAULT) " gespielt!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(11) "Vous jouez le " COLOR(YELLOW) "Chant du Soleil" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
)

DEFINE_MESSAGE(0x089D, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(16) "You played the " COLOR(LIGHTBLUE) "Song of Time" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE COLOR(LIGHTBLUE) "Hymne der Zeit " COLOR(DEFAULT) "gespielt!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE SHIFT(9) "Vous jouez le " COLOR(LIGHTBLUE) "Chant du Temps" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
)

DEFINE_MESSAGE(0x089E, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(9) "You played the " COLOR(PURPLE) "Song of Storms" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE COLOR(PURPLE) "Hymne des" COLOR(DEFAULT) " " COLOR(PURPLE) "Sturms " COLOR(DEFAULT) "gespielt!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE "Vous jouez le " COLOR(PURPLE) "Chant des Tempêtes" COLOR(DEFAULT) "!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
)

DEFINE_MESSAGE(0x089F, TEXTBOX_TYPE_OCARINA, TEXTBOX_POS_VARIABLE,
MSG(/* MISSING */)
,
MSG(
QUICKTEXT_ENABLE SHIFT(4) "You played the " COLOR(YELLOW) "Scarecrow's Song" COLOR(DEFAULT) ".\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE COLOR(YELLOW) "Vogelscheuchen-Polka " COLOR(DEFAULT) "gespielt!\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
,
MSG(
QUICKTEXT_ENABLE "Vous jouez le " COLOR(YELLOW) "Chant de l'Epouvantail" COLOR(DEFAULT) "\n"
"\n"
"\n"
QUICKTEXT_DISABLE
)
)

/* end of ocarina stuff */

/*
 * The following two messages should be kept last and in this order.
 * Message 0xFFFD must be last to not break the message debugger (see R_MESSAGE_DEBUGGER_TEXTID).
 * Message 0xFFFC must be immediately before message 0xFFFD to not break Font_LoadOrderedFont.
 */
DEFINE_MESSAGE_FFFC(0xFFFC, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE,
MSG(
"０１２３４５６７８９あいうえおかきくけこ\n"
"さしすせそたちつてとなにぬねのはひふへほ\n"
"まみむめもやゆよらりるれろわをんぁぃぅぇ\n"
"ぉっゃゅょがぎぐげござじずぜぞだぢづでど\n"
"ばびぶべぼぱぴぷぺぽアイウエオカキクケコ\n"
"サシスセソタチツテトナニヌネノハヒフヘホ\n"
"マミムメモヤユヨラリルレロワヲンァィゥェ\n"
"ォッャュョガギグゲゴザジズゼゾダヂヅデド\n"
"バビブベボパピプペポヴＡＢＣＤＥＦＧＨＩ\n"
"ＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺａｂｃ\n"
"ｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗ\n"
"ｘｙｚ　┯？！：−（）゛゜，．／"
)
,
MSG(
"0123456789\n"
"ABCDEFGHIJKLMN\n"
"OPQRSTUVWXYZ\n"
"abcdefghijklmn\n"
"opqrstuvwxyz\n"
" -.\n"
)
,
MSG(/* UNUSED */)
,
MSG(/* UNUSED */)
)
DEFINE_MESSAGE(0xFFFD, TEXTBOX_TYPE_BLACK, TEXTBOX_POS_VARIABLE, MSG(), MSG(), MSG(), MSG())
